apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haas
  template:
    metadata:
      labels:
        app: haas
    spec:
      hostNetwork: true
      containers:
      - name: homeassistant
        image: homeassistant/home-assistant:latest
        env:
        - name: TZ
          value: "Europe/Bucharest"
        ports:
          - containerPort: 8123
        resources: {}
        volumeMounts:
          - mountPath: /config
            name: homeassistant-config
          - mountPath: /etc/localtime
            name: homeassistant-time
            readOnly: true
      restartPolicy: Always
      volumes:
        - name: homeassistant-config
          persistentVolumeClaim:
            claimName: homeassistant-config-pvc
        - name: homeassistant-time
          persistentVolumeClaim:
            claimName: homeassistant-time-pvc
            readOnly: true
status: {}
