apiVersion: apps/v1
kind: Deployment
metadata:
  name: z2m
  namespace: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: z2m
  template:
    metadata:
      labels:
        app: z2m
    spec:
      # nodeSelector:
      #   kubernetes.io/hostname: raspberry-finn
      containers:
        - name: zigbee2mqtt
          image: koenkk/zigbee2mqtt:latest-dev
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Europe/Berlin
            - name: "ZIGBEE2MQTT_DATA"
              value: "/data"
            - name: ZIGBEE2MQTT_CONFIG_MQTT_SERVER # optional - can also be configured in the configuration.yaml in the configmap
              value: "mqtt://mosquitto"
          securityContext:
            privileged: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: z2m-data
              mountPath: /data
            - name: zigbee2mqtt-config
              mountPath: /app/configuration.yaml
              subPath: configuration.yaml
            # - name: zigbee2mqtt-udev
            #   mountPath: /run/udev
            # - name: ttyacm
            #   mountPath: /dev/ttyACM0
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
      volumes:
        - name: z2m-data
          persistentVolumeClaim:
            claimName: z2m-data
        - name: zigbee2mqtt-config
          configMap:
            name: zigbee2mqtt-config
        # - name: usb
        #   hostPath:
        #     path: /dev/ttyUSB0
        # - name: udev
        #   hostPath:
        #     path: /run/udev
