apiVersion: apps/v1
kind: Deployment
metadata:
  name: z2m
  namespace: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: z2m
  template:
    metadata:
      labels:
        app: z2m
    spec:
      # nodeSelector:
      #   kubernetes.io/hostname: raspberry-finn
      containers:
      - name: z2m
        image: koenkk/zigbee2mqtt:latest
        env:
          - name: TZ
            value: Europe/Bucharest
          - name: ZIGBEE2MQTT_CONFIG_MQTT_SERVER
            value: "mqtt://mqtt-service.homeassistant.svc.cluster.local:1883"
          - name: ZIGBEE2MQTT_CONFIG_MQTT_USER
            value: "mqtt"
          - name: ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD
            value: "pass4mqtt"
          - name: ZIGBEE2MQTT_CONFIG_HOMEASSISTANT
            value: "true"
        securityContext:
          privileged: true
        ports:
          - containerPort: 8080
        serial:
          port: 'tcp://172.16.23.19:8888'
          adapter: auto

        volumeMounts:
          - name: z2m-data
            mountPath: /app/data
          # - name: usb
          #   mountPath: /dev/ttyUSB0
          # - name: udev
          #   mountPath: /run/udev
      volumes:
        - name: z2m-data
          persistentVolumeClaim:
            claimName: z2m-data
        # - name: usb
        #   hostPath:
        #     path: /dev/ttyUSB0
        # - name: udev
        #   hostPath:
        #     path: /run/udev
